### ISSUE TITLE
Request Checker for detection existence.

### ISSUE THREAD

**Issue by Andi-IM** [Pujidhiyanabila/acne_detection#1]
https://github.com/Pujidhiyanabila/acne_detection/blob/1c65c1737d540855e14a9a1ef48c819a33c25e8e/acne_detection/lib/Detection/Camera_Preview_Page.dart#L20

pada baris tersebut terdapat List, nah lakukan pengecekan apakah list tersebut berisi deteksi atau tidak.

**Comment by Andi-IM** [comment]
kayanya disini:

https://github.com/Pujidhiyanabila/acne_detection/blob/1c65c1737d540855e14a9a1ef48c819a33c25e8e/acne_detection/lib/Detection/Camera_Preview_Page.dart#L96

**Comment by Pujidhiyanabila** [comment]
@override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        appBar: AppBar(
            title: const Text('Results')),
        body: Center(
          child: false
              ? Column(
                children: [
                  Image.file(File(widget.picture.path)),
                  Container(
                    alignment: Alignment.centerLeft,
                    margin: const EdgeInsets.symmetric(
                      vertical: 2,
                      horizontal: 10,
                    ),
                    child: const Text(
                      "Tidak Terdetection",
                      maxLines: 2,
                      style:
                      TextStyle(
                        fontSize: 20,
                        fontFamily: 'avenir',
                        color: ColorStyles.textColor,
                        overflow: TextOverflow.ellipsis,
                        fontWeight: FontWeight.w800,
                      ),
                    ),
                  )
                ],
              )
              : Column(
                children: [
                  _buildBoxes(),
                  Container(
                    alignment: Alignment.centerLeft,
                    margin: const EdgeInsets.symmetric(
                      vertical: 2,
                      horizontal: 10,
                    ),
                    child: const Text(
                      "Terdetection",
                      maxLines: 2,
                      style:
                      TextStyle(
                        fontSize: 20,
                        fontFamily: 'avenir',
                        color: ColorStyles.textColor,
                        overflow: TextOverflow.ellipsis,
                        fontWeight: FontWeight.w800,
                      ),
                    ),
                  ),
                ],
              ),
        ),
      ),
    );
  }

Berarti ada pengaruh dari sana?

**Comment by Andi-IM** [comment]
disini cek aja pake if

https://github.com/Pujidhiyanabila/acne_detection/blob/1c65c1737d540855e14a9a1ef48c819a33c25e8e/acne_detection/lib/Detection/Camera_Preview_Page.dart#L211

if kalo List<Rect> atau List<Label> ada isinya, baru itu....

**Comment by Andi-IM** [comment]
> @OverRide Widget build(BuildContext context) { return SafeArea( child: Scaffold( appBar: AppBar( title: const Text('Results')), body: Center( child: false ? Column( children: [ Image.file(File(widget.picture.path)), Container( alignment: Alignment.centerLeft, margin: const EdgeInsets.symmetric( vertical: 2, horizontal: 10, ), child: const Text( "Tidak Terdetection", maxLines: 2, style: TextStyle( fontSize: 20, fontFamily: 'avenir', color: ColorStyles.textColor, overflow: TextOverflow.ellipsis, fontWeight: FontWeight.w800, ), ), ) ], ) : Column( children: [ _buildBoxes(), Container( alignment: Alignment.centerLeft, margin: const EdgeInsets.symmetric( vertical: 2, horizontal: 10, ), child: const Text( "Terdetection", maxLines: 2, style: TextStyle( fontSize: 20, fontFamily: 'avenir', color: ColorStyles.textColor, overflow: TextOverflow.ellipsis, fontWeight: FontWeight.w800, ), ), ), ], ), ), ), ); }
> 
> Berarti ada pengaruh dari sana?

mungkin, soalnya kan ga null belum tentu kosong :v

**Comment by Pujidhiyanabila** [comment]
> disini cek aja pake if
> 
> https://github.com/Pujidhiyanabila/acne_detection/blob/1c65c1737d540855e14a9a1ef48c819a33c25e8e/acne_detection/lib/Detection/Camera_Preview_Page.dart#L211
> 
> if kalo List atau List ada isinya, baru itu....

kayak gimana contohnya?

**Comment by Pujidhiyanabila** [comment]
> > @OverRide Widget build(BuildContext context) { return SafeArea( child: Scaffold( appBar: AppBar( title: const Text('Results')), body: Center( child: false ? Column( children: [ Image.file(File(widget.picture.path)), Container( alignment: Alignment.centerLeft, margin: const EdgeInsets.symmetric( vertical: 2, horizontal: 10, ), child: const Text( "Tidak Terdetection", maxLines: 2, style: TextStyle( fontSize: 20, fontFamily: 'avenir', color: ColorStyles.textColor, overflow: TextOverflow.ellipsis, fontWeight: FontWeight.w800, ), ), ) ], ) : Column( children: [ _buildBoxes(), Container( alignment: Alignment.centerLeft, margin: const EdgeInsets.symmetric( vertical: 2, horizontal: 10, ), child: const Text( "Terdetection", maxLines: 2, style: TextStyle( fontSize: 20, fontFamily: 'avenir', color: ColorStyles.textColor, overflow: TextOverflow.ellipsis, fontWeight: FontWeight.w800, ), ), ), ], ), ), ), ); }
> > Berarti ada pengaruh dari sana?
> 
> mungkin, soalnya kan ga null belum tentu kosong :v

iyaa juga sihh

**Comment by Andi-IM** [comment]
btw rapihin dong,

pake teknik menggunakan simbol di sebelah tombol 1 di keyboard => `

contoh
```
 ```dart
 print("test");```
 ```

hasilnya 

 ```dart
 print("test");
```

**Comment by Andi-IM** [comment]
> > disini cek aja pake if
> > https://github.com/Pujidhiyanabila/acne_detection/blob/1c65c1737d540855e14a9a1ef48c819a33c25e8e/acne_detection/lib/Detection/Camera_Preview_Page.dart#L211
> > 
> > if kalo List atau List ada isinya, baru itu....
> 
> kayak gimana contohnya?

https://www.geeksforgeeks.org/flutter-outputting-widgets-conditionally/

**Comment by Andi-IM** [comment]
![image](https://github.com/Pujidhiyanabila/acne_detection/assets/21165698/c71e3e4c-117e-4895-976c-7b709ec9abe2)

yah make SDK tinggi pula, update duls

**Comment by Pujidhiyanabila** [comment]
> > > disini cek aja pake if
> > > https://github.com/Pujidhiyanabila/acne_detection/blob/1c65c1737d540855e14a9a1ef48c819a33c25e8e/acne_detection/lib/Detection/Camera_Preview_Page.dart#L211
> > > 
> > > if kalo List atau List ada isinya, baru itu....
> > 
> > 
> > kayak gimana contohnya?
> 
> https://www.geeksforgeeks.org/flutter-outputting-widgets-conditionally/

@override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        appBar: AppBar(
            title: const Text('Results')),
        body: Center(
          child: Column(
            children: <Widget>[
              Column(
              children: [
                Image.file(File(widget.picture.path)),
                Container(
                  alignment: Alignment.centerLeft,
                  margin: const EdgeInsets.symmetric(
                    vertical: 2,
                    horizontal: 10,
                  ),
                  child: const Text(
                    "Tidak Terdeteksi",
                    style:
                    TextStyle(
                      fontSize: 20,
                      fontFamily: 'avenir',
                      color: ColorStyles.textColor,
                      overflow: TextOverflow.ellipsis,
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                )
              ],),
              if (_isLoading)
                Column(
                  children: [
                    _buildBoxes(),
                    Container(
                      alignment: Alignment.centerLeft,
                      margin: const EdgeInsets.symmetric(
                        vertical: 2,
                        horizontal: 10,
                      ),
                      child: const Text(
                        "Terdeteksi",
                        maxLines: 2,
                        style:
                        TextStyle(
                          fontSize: 20,
                          fontFamily: 'avenir',
                          color: ColorStyles.textColor,
                          overflow: TextOverflow.ellipsis,
                          fontWeight: FontWeight.w800,
                        ),
                      ),
                    ),
                  ],
                ),
            ],
          )
        )
      ),
    );
Gini gasihh, tapi salah wkwkwk

**Comment by Andi-IM** [comment]
nambahin nih di https://github.com/Pujidhiyanabila/acne_detection/pull/2

https://github.com/Andi-IM/acne_detection/blob/8e82ea737c2b31568235ae9d509ecad7cdf45ef2/acne_detection/lib/Detection/Camera_Preview_Page.dart#L230

kodenya simple bet wkwk

**Comment by Pujidhiyanabila** [comment]
> nambahin nih di #2
> 
> https://github.com/Andi-IM/acne_detection/blob/8e82ea737c2b31568235ae9d509ecad7cdf45ef2/acne_detection/lib/Detection/Camera_Preview_Page.dart#L230
> 
> kodenya simple bet wkwk

Sudah bisa ndii, Terimakasiii
